program main
  use cudafor
  implicit none
  integer :: device_id, istat, device_count
  
  print *, "CUDA Fortran Test Start..."

  ! 1. 감지된 GPU 개수 확인
  istat = cudaGetDeviceCount(device_count)
  if (istat /= 0) then
     print *, "Error: GPU를 찾을 수 없거나 드라이버 문제 발생."
     stop
  end if
  print *, "Detected GPU Count:", device_count

  ! 2. 현재 사용 중인 디바이스 ID 확인
  ! (성공 시 istat에 0이 반환됩니다)
  istat = cudaGetDevice(device_id)
  
  if (istat == 0) then
      print *, "Success! Current Device ID:", device_id
      print *, "Hello, CUDA Fortran is working perfectly!"
  else
      print *, "Error: Failed to get device ID."
  endif

end program main